"""
make_og_image.py

Renders assets/og-image.png -- the 1200x630 link-preview card LinkedIn, Slack,
X, etc. show when the dashboard URL is shared (referenced by the og:image /
twitter:image tags in index.html).

The card is a static snapshot: it draws the same per-category daily-trend
sparklines the live "Coverage trend" panel shows, from whatever is in
data/latest.json at the time this script runs. It is NOT regenerated by the
GitHub Actions cron -- re-run it by hand if you want the thumbnail to reflect
newer data or a taxonomy/palette change:

    pip install pillow          # dev-only; deliberately not in requirements.txt
    python scripts/make_og_image.py

Why a PNG and not an SVG: LinkedIn (and most scrapers) won't render SVG
previews. 1200x630 (~1.9:1) is the size they all crop to.

Uses only aggregate counts already in data/latest.json -- no article text,
no X content -- consistent with the project's scope guardrail.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).parent.parent
DATA_PATH = ROOT / "data" / "latest.json"
OUT_PATH = ROOT / "assets" / "og-image.png"

W, H = 1200, 630
S = 2  # supersample factor; drawn at 2x then downsampled for smooth edges

# Dashboard dark-mode palette (see style.css)
BG = "#0d0d0d"
SURFACE = "#1a1a19"
SURFACE_2 = "#232320"
BORDER = "#2c2c2a"
TEXT = "#ffffff"
TEXT_SECONDARY = "#c3c2b7"
TEXT_MUTED = "#898781"

# (category key, short label, dark-mode color) -- same order/colors as style.css
CATEGORIES = [
    ("chemical", "Chemical", "#3987e5"),
    ("biological", "Biological", "#d95926"),
    ("nuclear", "Nuclear", "#199e70"),
    ("radiological", "Radiological", "#c98500"),
    ("explosives", "Explosives", "#d55181"),
    ("autonomous_weapons", "Autonomous", "#008300"),
    ("directed_energy", "Directed Energy", "#9085e9"),
]

FONT_CANDIDATES = {
    "regular": ["segoeui.ttf", "arial.ttf", "DejaVuSans.ttf"],
    "bold": ["segoeuib.ttf", "arialbd.ttf", "DejaVuSans-Bold.ttf"],
    "semibold": ["seguisb.ttf", "segoeuib.ttf", "arialbd.ttf", "DejaVuSans-Bold.ttf"],
}
FONT_DIRS = [Path("C:/Windows/Fonts"), Path("/usr/share/fonts/truetype/dejavu"), Path("/Library/Fonts")]


def font(kind: str, size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for name in FONT_CANDIDATES[kind]:
        for d in FONT_DIRS:
            p = d / name
            if p.exists():
                return ImageFont.truetype(str(p), size * S)
    return ImageFont.load_default()


def daily_counts(items: list[dict], cat: str, days: int) -> list[int]:
    """Same UTC-day bucketing as renderTrend() in app.js."""
    today = datetime.now(timezone.utc).date()
    keys = [(today - timedelta(days=i)).isoformat() for i in range(days - 1, -1, -1)]
    index = {k: i for i, k in enumerate(keys)}
    counts = [0] * days
    for item in items:
        if cat not in item.get("categories", []):
            continue
        try:
            d = datetime.fromisoformat(item["published_date"]).astimezone(timezone.utc).date().isoformat()
        except (KeyError, ValueError):
            continue
        if d in index:
            counts[index[d]] += 1
    return counts


def smooth(points: list[tuple[float, float]], steps: int = 8) -> list[tuple[float, float]]:
    """Catmull-Rom-ish smoothing so the sparkline matches Chart.js's tension curve."""
    if len(points) < 3:
        return points
    out: list[tuple[float, float]] = []
    pts = [points[0]] + points + [points[-1]]
    for i in range(1, len(pts) - 2):
        p0, p1, p2, p3 = pts[i - 1], pts[i], pts[i + 1], pts[i + 2]
        for s in range(steps):
            t = s / steps
            t2, t3 = t * t, t * t * t
            x = 0.5 * ((2 * p1[0]) + (-p0[0] + p2[0]) * t + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
                       + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3)
            y = 0.5 * ((2 * p1[1]) + (-p0[1] + p2[1]) * t + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
                       + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3)
            out.append((x, y))
    out.append(points[-1])
    return out


def hex_rgba(h: str, alpha: int) -> tuple[int, int, int, int]:
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), alpha)


def main() -> None:
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    items = data.get("items", [])
    days = int(data.get("retention_days", 14))

    # RGB canvas + RGBA draw mode: that's the combination Pillow alpha-blends
    # for. (An RGBA canvas *replaces* pixels, so the translucent area fills
    # under the sparklines would come out opaque and hide the line.)
    img = Image.new("RGB", (W * S, H * S), BG)
    d = ImageDraw.Draw(img, "RGBA")

    def px(v: float) -> int:
        return int(round(v * S))

    pad = 64

    # Accent bar + eyebrow
    d.rounded_rectangle([px(pad), px(58), px(pad + 44), px(63)], radius=px(2), fill="#3987e5")
    d.text((px(pad), px(78)), "OPEN-SOURCE SIGNAL DETECTION", font=font("bold", 17), fill=TEXT_MUTED)

    # Title
    d.text((px(pad), px(112)), "CBRN-E & Novel Weapons", font=font("bold", 62), fill=TEXT)
    d.text((px(pad), px(184)), "OSINT Dashboard", font=font("bold", 62), fill=TEXT)

    # Tagline
    d.text(
        (px(pad), px(272)),
        "Publicly reported news coverage, classified into seven threat",
        font=font("regular", 25), fill=TEXT_SECONDARY,
    )
    d.text(
        (px(pad), px(306)),
        "categories and refreshed automatically every 6 hours.",
        font=font("regular", 25), fill=TEXT_SECONDARY,
    )

    # Sparkline row -- a miniature of the live "Coverage trend" panel
    n = len(CATEGORIES)
    gap = 14
    cell_w = (W - 2 * pad - gap * (n - 1)) / n
    cell_h = 122
    top = 384
    for i, (key, label, color) in enumerate(CATEGORIES):
        x0 = pad + i * (cell_w + gap)
        x1 = x0 + cell_w
        d.rounded_rectangle(
            [px(x0), px(top), px(x1), px(top + cell_h)],
            radius=px(10), fill=SURFACE_2, outline=BORDER, width=S,
        )
        d.text((px(x0 + 12), px(top + 10)), label, font=font("semibold", 15), fill=color)

        counts = daily_counts(items, key, days)
        peak = max(max(counts), 1)
        gx0, gx1 = x0 + 12, x1 - 12
        gy_top, gy_bot = top + 44, top + cell_h - 14
        pts = [
            (gx0 + (gx1 - gx0) * j / (len(counts) - 1), gy_bot - (gy_bot - gy_top) * c / peak)
            for j, c in enumerate(counts)
        ]
        # Clamp: the spline can undershoot below the baseline next to zero days.
        curve = [(x, min(max(y, gy_top), gy_bot)) for x, y in smooth(pts)]
        area = [(px(gx0), px(gy_bot))] + [(px(x), px(y)) for x, y in curve] + [(px(gx1), px(gy_bot))]
        d.polygon(area, fill=hex_rgba(color, 40))
        d.line([(px(x), px(y)) for x, y in curve], fill=color, width=px(2.5), joint="curve")
        d.line([(px(gx0), px(gy_bot)), (px(gx1), px(gy_bot))], fill=BORDER, width=S)

    # Footer
    d.text((px(pad), px(560)), "matthewcarlpreston.github.io/cbrne-threat-dashboard",
           font=font("semibold", 20), fill=TEXT_SECONDARY)
    guard = "Public-signal only \u2014 no technical weapons content"
    gf = font("regular", 18)
    gw = d.textlength(guard, font=gf) / S
    d.text((px(W - pad - gw), px(563)), guard, font=gf, fill=TEXT_MUTED)

    out = img.resize((W, H), Image.LANCZOS)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    out.save(OUT_PATH, "PNG", optimize=True)
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size / 1024:.0f} KB, {W}x{H})")


if __name__ == "__main__":
    main()
